# Generated by Django 2.2.2 on 2019-10-14 03:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notice_for_all',
            new_name='notice',
        ),
    ]
