# Generated by Django 2.2.2 on 2019-09-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name_plural': 'Employee Blogs'},
        ),
        migrations.AlterField(
            model_name='blogs',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='uploads/blogs'),
        ),
    ]
