# Generated by Django 2.2.2 on 2019-09-10 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_no', models.IntegerField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='user_image')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=225)),
                ('van_no', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
