# Generated by Django 2.2.2 on 2019-09-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=0, null=True)),
                ('width_field', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(default='Enter your name', max_length=30)),
                ('extra_info', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('driver_address', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=0, null=True)),
                ('width_field', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(default='Enter your name', max_length=30)),
                ('staff_address', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('extra_info', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
