# Generated by Django 2.2.2 on 2019-10-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_done',
            name='work_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task_done',
            name='work_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
