# Generated by Django 2.2.2 on 2019-10-13 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191013_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_done',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bin.Area'),
        ),
        migrations.AlterField(
            model_name='task_done',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
