# Generated by Django 2.2.2 on 2019-10-13 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191013_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_done',
            name='work_date',
        ),
        migrations.RemoveField(
            model_name='task_done',
            name='work_time',
        ),
        migrations.AddField(
            model_name='task_done',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
