# Generated by Django 2.2.2 on 2019-10-06 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bin', '0007_auto_20191006_2100'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20190917_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time', models.TimeField()),
                ('area', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bin.Area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
