# Generated by Django 2.2.2 on 2019-10-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191013_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_done',
            name='date_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
