# Generated by Django 2.2.2 on 2019-10-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191015_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_done',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
