# Generated by Django 2.2.2 on 2019-09-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190912_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='accounts/usersimage'),
        ),
    ]
